"""edit cases table

Revision ID: 22448a6f854c
Revises: 46c0c717b952
Create Date: 2024-01-22 22:40:23.850353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22448a6f854c'
down_revision: Union[str, None] = '46c0c717b952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'cases', ['salesforce_case_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cases', type_='unique')
    # ### end Alembic commands ###
