"""vertical table removal

Revision ID: 7db2df20bce8
Revises: b91b3e576458
Create Date: 2024-01-25 15:21:45.510776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7db2df20bce8'
down_revision: Union[str, None] = 'b91b3e576458'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verticals')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verticals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vertical_name', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='verticals_pkey')
    )
    # ### end Alembic commands ###
