"""db version 2 adding columns to the case

Revision ID: a5000e28f9c8
Revises: bd68cbf57a66
Create Date: 2023-12-22 16:09:21.867566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5000e28f9c8'
down_revision: Union[str, None] = 'bd68cbf57a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('salesforce_case_number', sa.Integer(), nullable=False))
    op.add_column('cases', sa.Column('jira_escalation_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'jira_escalation_number')
    op.drop_column('cases', 'salesforce_case_number')
    # ### end Alembic commands ###
