"""edit case topic

Revision ID: b91b3e576458
Revises: 22448a6f854c
Create Date: 2024-01-22 23:23:50.307794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b91b3e576458'
down_revision: Union[str, None] = '22448a6f854c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('case_type', sa.String(length=60), nullable=False))
    op.drop_column('cases', 'case_topic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('case_topic', sa.VARCHAR(length=60), autoincrement=False, nullable=False))
    op.drop_column('cases', 'case_type')
    # ### end Alembic commands ###
